version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: InspaceDB
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - inspace-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: InspaceAPI
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - inspace-network

volumes:
  pgdata: {}

networks:
  inspace-network:
    driver: bridge

